-- Generated from generator/demo_specs/aws-indonesia-islamic-finance-digital.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-indonesia-islamic-finance-digital
-- This is the schema that is actually deployed for ID_ISLAMIC_FINANCE_DIGITAL.

-- Alerts fire on the bottom tail of Products Launched
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_PRODUCTS_LAUNCHED) AS T
  FROM RAW.APP_EVENTS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_PRODUCTS_LAUNCHED <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_PRODUCTS_LAUNCHED), 2) AS AVG_PRODUCTS_LAUNCHED,
  ROUND(AVG(f.KPI_CONVERSION_RATE), 2) AS AVG_CONVERSION_RATE,
  ROUND(AVG(f.KPI_AVG_INVESTMENT), 2) AS AVG_INVESTMENT,
  ROUND(AVG(f.KPI_SHARIAH_COMPLIANCE), 2) AS AVG_SHARIAH_COMPLIANCE
FROM RAW.APP_EVENTS f
JOIN RAW.PRODUCT_DOCS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_PRODUCTS_LAUNCHED), 2) AS AVG_PRODUCTS_LAUNCHED,
  ROUND(AVG(f.KPI_CONVERSION_RATE), 2) AS AVG_CONVERSION_RATE,
  ROUND(AVG(f.KPI_AVG_INVESTMENT), 2) AS AVG_INVESTMENT,
  ROUND(AVG(f.KPI_SHARIAH_COMPLIANCE), 2) AS AVG_SHARIAH_COMPLIANCE
FROM RAW.APP_EVENTS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_SHARIAH_COMPLIANCE) AS KPI_SHARIAH_COMPLIANCE, AVG(KPI_PRODUCTS_LAUNCHED) AS KPI_PRODUCTS_LAUNCHED, AVG(KPI_CONVERSION_RATE) AS KPI_CONVERSION_RATE, AVG(KPI_AVG_INVESTMENT) AS KPI_AVG_INVESTMENT FROM RAW.APP_EVENTS),
     en AS (SELECT SUM(KPI_DIGITAL_ISLAMIC_AUM) AS KPI_DIGITAL_ISLAMIC_AUM, SUM(KPI_ACTIVE_USERS) AS KPI_ACTIVE_USERS, SUM(KPI_APP_DAU) AS KPI_APP_DAU FROM RAW.PRODUCT_DOCS)
  SELECT 1 AS SORT_ORDER, 'Digital Islamic AUM' AS TITLE, KPI_DIGITAL_ISLAMIC_AUM AS VALUE_NUM, 'Rp' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_DIGITAL_ISLAMIC_AUM) / 1000000000000), 1) AS DECIMAL(38,1))) || 'T' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Active Users' AS TITLE, KPI_ACTIVE_USERS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_ACTIVE_USERS) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Shariah Compliance' AS TITLE, KPI_SHARIAH_COMPLIANCE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SHARIAH_COMPLIANCE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Products Launched' AS TITLE, KPI_PRODUCTS_LAUNCHED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PRODUCTS_LAUNCHED)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'App DAU' AS TITLE, KPI_APP_DAU AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_APP_DAU) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Conversion Rate' AS TITLE, KPI_CONVERSION_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CONVERSION_RATE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Avg Investment' AS TITLE, KPI_AVG_INVESTMENT AS VALUE_NUM, 'Rp' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_AVG_INVESTMENT) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
