-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Digital Islamic Banking
-- ============================================================================
USE DATABASE ISLAMIC_DIGITAL_BANKING;
USE SCHEMA ML;

-- ML.FORECAST: DEPOSIT_GROWTH_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.DEPOSIT_GROWTH_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.DEPOSIT_GROWTH_METRICS'),
  SERIES_COLNAME => 'SEGMENT',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.DEPOSIT_GROWTH_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.DEPOSIT_GROWTH_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

