-- ============================================================================
-- 99_RESET.SQL — Reset Digital Islamic Banking to clean demo state
-- ============================================================================
USE DATABASE ISLAMIC_DIGITAL_BANKING;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_REFRESH_CUSTOMER_360 SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SCORE_CHURN SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST_DEPOSITS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.CUSTOMER_360 REFRESH;
ALTER DYNAMIC TABLE CURATED.DEPOSIT_GROWTH_METRICS REFRESH;
ALTER DYNAMIC TABLE CURATED.CHURN_RISK_SCORE REFRESH;
ALTER DYNAMIC TABLE CURATED.CAMPAIGN_ROI REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM ISLAMIC_DIGITAL_BANKING.RAW.CUSTOMERS → 500000
-- SELECT COUNT(*) FROM ISLAMIC_DIGITAL_BANKING.RAW.TRANSACTIONS → 5000000
-- SELECT COUNT(*) FROM ISLAMIC_DIGITAL_BANKING.RAW.APP_EVENTS → 10000000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_FORECAST_DEPOSITS RESUME;
ALTER TASK IF EXISTS APP.TASK_SCORE_CHURN RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_CUSTOMER_360 RESUME;
